name: Release Build

on:
  release:
    types: [published, edited]

jobs:
  build:
    permissions:
      contents: write
    runs-on: windows-latest

    strategy:
      matrix:
        target:
          - win-x64

    steps:
      - name: Checkout code
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6.1.0

      - name: Setup .NET
        uses: actions/setup-dotnet@a98b56852c35b8e3190ac28c8c2271da59106c68 # v6

      - name: Build
        run: |
          $version = "${{ github.event.release.tag_name }}".Substring(1)
          dotnet publish -p:Version=$version -r ${{ matrix.target }} -o out/${{ matrix.target }} -- ./src/node-service/BitcoinNodeService.csproj
        shell: pwsh
        

      - name: Archive and Hash
        run: |
          Compress-Archive -Path ./out/${{ matrix.target }}/* -DestinationPath ./out/${{ matrix.target }}.zip -CompressionLevel Optimal -Force
          Get-FileHash -Path ./out/${{ matrix.target }}.zip -Algorithm SHA256 | ForEach-Object { $_.Hash } | Out-File -FilePath ./out/${{ matrix.target }}.zip.sha256
        shell: pwsh

      - name: Upload
        run: gh release upload ${{ github.event.release.tag_name }} ./out/${{ matrix.target }}.zip ./out/${{ matrix.target }}.zip.sha256 --clobber
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: pwsh
