name: Test Build Configuration

on:
  workflow_dispatch:
    inputs:
      targets:
        description: Comma separated list of string targets to build
        default: '"win-x64"'

permissions:
  contents: read
jobs:
  build:
    runs-on: windows-latest

    strategy:
      matrix:
        target: ${{ fromJson(format('[{0}]', inputs.targets || '"win-x64""')) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0

      - name: Setup .NET
        uses: actions/setup-dotnet@26b0ec14cb23fa6904739307f278c14f94c95bf1 # v5

      - name: Build
        run: dotnet publish -p:Version=0.0.0-test -r ${{ matrix.target }} -o out/${{ matrix.target }} -- ./src/node-service/BitcoinNodeService.csproj

      - name: Archive and Hash
        run: |
          New-Item -Name artifacts -ItemType Directory
          Compress-Archive -Path ./out/${{ matrix.target }}/* -DestinationPath ./artifacts/${{ matrix.target }}.zip -CompressionLevel Optimal -Force
          Get-FileHash -Path ./artifacts/${{ matrix.target }}.zip -Algorithm SHA256 | ForEach-Object { $_.Hash } | Out-File -FilePath ./artifacts/${{ matrix.target }}.zip.sha256
        shell: pwsh

      - name: Upload
        uses: actions/upload-artifact@330a01c490aca151604b8cf639adc76d48f6c5d4 # v5
        with:
          name: build-artifacts
          path: ./artifacts/*
